Add: Sandbox dataset description + minor changes
encord-team/encord-active pull request #126
Opened 2023-01-26 15:25 UTC by nikolaj-encord

2023-01-30 14:14 UTC, frederik-encord requested changes

2023-01-30 14:14 UTC, frederik-encord commented on docs/docs/cli/download-sandbox-data.md
> +If you have a dataset you'd like us to include in the sandbox please submit an issue on Github or contact us directly. We'd love to help!
```suggestion
If you have a dataset you'd like us to include in the sandbox please submit an [issue](https://github.com/encord-team/encord-active/issues) on Github or contact us directly at [active@encord.com](mailto:active@encord.com). 
We'd love to help!
```

2023-01-30 14:14 UTC, frederik-encord commented on docs/docs/cli/download-sandbox-data.md
> +- **Categories:**  7 plane categories
81 classes no? Dont know what the 7 planes would be? Is that leftover from `rareplanes`?

2023-01-30 14:14 UTC, frederik-encord commented on docs/docs/cli/download-sandbox-data.md
> +- **Author:**
Perhaps add unknown or something?

2023-01-30 14:14 UTC, frederik-encord commented on docs/docs/cli/download-sandbox-data.md
> +
No examples?

2023-01-30 14:14 UTC, frederik-encord commented on docs/docs/cli/download-sandbox-data.md
> +- **Read more:** [Webpage](https://www.notion.so/Jan-9-2023-c23ea70fe8b64b889dc8b8ad4f77ad18) & [GitHub](https://github.com/GorkemP/labeled-images-for-ulcerative-colitis)
No examples? I suppose it is on purpose on this one?

2023-01-30 14:14 UTC, frederik-encord commented on docs/docs/cli/initialising-project-from-image-directories.md
> +# Initialising from Image Directory
```suggestion
# Initializing from Image Directory
```

2023-01-30 14:31 UTC, nikolaj-encord reviewed
Accepted requested changes. I have pulled it out as a draft so I can add the information on the dataset that is missing.

2023-01-30 23:25 UTC, nikolaj-encord reviewed
All comments approved from my side Fred.

2023-01-31 07:59 UTC, frederik-encord approved these changes

2023-01-31 08:04 UTC, merged