docs (metrics): update example metric
encord-team/encord-active pull request #192
Opened 2023-02-17 17:11 UTC by eloy-encord

2023-02-21 17:50 UTC, Gorkem-Encord requested changes
In these example projects, both image-level and object-level writing is happening in the same iteration loop. We do not allow such thing and it may confuse the users, so we should note somewhere that 'you can either create an image-level metric or an object-level metric, not both at the same time'. We can also divide the iterating over data_units into two and comment one of them to not cause any confusion.

2023-02-22 07:41 UTC, frederik-encord commented
What might want to do is having separate (sub)classes for image level and object level metrics and then enforce that they call the writer with the right parameters to avoid this confusion. Perhaps not in this PR though.

2023-02-22 12:23 UTC, frederik-encord requested changes

2023-02-22 12:23 UTC, frederik-encord commented on docs/docs/metrics/write-your-own.md
> +E.g. you can make a
```suggestion
For example, you can make a
```

2023-02-22 12:23 UTC, frederik-encord commented on src/encord_active/lib/metrics/example.py
> +E.g. you can make a
```suggestion
For example, you can make a
```

2023-02-22 12:23 UTC, frederik-encord commented on docs/docs/metrics/write-your-own.md
>  Your implementation should call `writer.write(<object_score>, <object>)` for every object in the iterator or use `writer.write(<frame_score>)` for every data unit in the iterator.
```suggestion
Your implementation should call `writer.write(<object_score>, <object>)` for every object in the iterator **OR** use `writer.write(<frame_score>)` for every data unit in the iterator.
```

2023-02-22 12:23 UTC, frederik-encord commented on docs/docs/metrics/write-your-own.md
>  Your implementation should call `writer.write(<object_score>, <object>)` for every object in the iterator or use `writer.write(<frame_score>)` for every data unit in the iterator.
Perhaps add a line saying (for now) that one should not do both in the same metric definition.

2023-02-22 14:21 UTC, frederik-encord approved these changes

2023-02-22 14:23 UTC, Gorkem-Encord approved these changes

2023-02-22 14:24 UTC, merged