feat(clone): local copy
encord-team/encord-active pull request #193
Opened 2023-02-17 17:25 UTC by yogesh-encord

2023-02-27 15:02 UTC, Encord-davids requested changes

2023-02-28 11:08 UTC, yogesh-encord commented on src/encord_active/app/actions_page/export_filter.py
> +def generate_create_project_form(header: str, num_rows: int, items_to_render: list[str]) -> Optional[RenderItems]:
We will probably be refactoring out most of theses to a different thing soon anyway, so leaving them here for now.

2023-03-02 17:41 UTC, Encord-davids submitted a review, later dismissed
LGTM ✅ 

@frederik-encord Can you please give this a test 🙏

2023-03-14 17:03 UTC, Encord-davids submitted a review, later dismissed

2023-03-14 17:10 UTC, Encord-davids approved these changes

2023-03-15 16:23 UTC, Encord-davids approved these changes

2023-03-16 13:19 UTC, merged