Feat (metrics): classification performance metrics
encord-team/encord-active pull request #231
Opened 2023-03-07 15:47 UTC by Gorkem-Encord

- Object and classification performance metrics can be visualized at the same time, their prediction files are kept separately under different folders.
- Classification metrics can be filtered according to the chosen classes.

For now, streamlit tab is created in `app/views/model_quality` tab, also classification performance metrics are also implemented here which is not ideal. However, there will be very fundamental changes in **Model quality** tab both in terms of reorganization of tabs and global filters. So, I haven't put too much effort to organizing and refactoring things that will already change very soon.

2023-03-09 11:15 UTC, frederik-encord requested changes
Issues that I found along the way were:
1. When I click the "Performance By  metrics", "False Positive", etc (not includint "Metrics") for a classification project, nothing happens?
2. Since the only thing that we need to do for existing projects (at least for object predictions) is to move the prediction files into an `objects` directory, perhaps we should do that automatically if we detect that there are model predictions available in the project? There may be some caveats around classifications stored as objects though? Don't think that any customer got that far though?

2023-03-09 11:15 UTC, frederik-encord commented on src/encord_active/lib/model_predictions/reader.py
> +class OntologyClassificationJSON(TypedDict):
If you like my other suggestion, this definition needs to go to the writer to avoid cyclic imports.

2023-03-09 11:15 UTC, frederik-encord commented on src/encord_active/app/views/model_quality.py
> +                st.altair_chart(metric_importance_chart, use_container_width=True)
This needs to be wrapped in a try catch as it will raise an error if there are not enough examples.

2023-03-10 16:56 UTC, Gorkem-Encord commented on src/encord_active/app/views/model_quality.py
> +                model_predictions_matched = match_predictions_and_labels(model_predictions, labels_all)
Indeed it is quite light, it corresponds to `compute_mAP_and_mAR` function, which adds extra column that indicates the  TP status.

2023-03-15 09:29 UTC, frederik-encord requested changes

2023-03-16 09:15 UTC, frederik-encord approved these changes

2023-03-16 09:51 UTC, merged