fix(export): Use mappings instead of renaming files
encord-team/encord-active pull request #273
Opened 2023-03-21 18:06 UTC by yogesh-encord

Now when exporting projects and creating subsets we create file mappings so as to avoid issues with versioning. This also fixes a versioning bug that discards you are changes when you're already on latest

2023-03-21 18:30 UTC, frederik-encord requested changes

2023-03-21 18:36 UTC, yogesh-encord commented on src/encord_active/lib/project/project_file_structure.py
> +            if (project_dir / "hash_mappings.json").exists()
There is a property, but is using that before __init__ finishes illegal?

2023-03-22 12:03 UTC, frederik-encord submitted a review, later dismissed

2023-03-22 12:05 UTC, frederik-encord approved these changes

2023-03-22 12:18 UTC, frederik-encord approved these changes

2023-03-22 12:19 UTC, merged