feat: adds a custom react exploere
encord-team/encord-active pull request #334
Opened 2023-04-20 15:59 UTC by Encord-davids

2023-04-24 09:23 UTC, Encord-davids commented on frontend_components/src/encord_active_components/frontend/src/components/explorer/Pagination.tsx
> +  if (totalItems % pageSize == 0) totalPages--;
good catch!

2023-04-24 09:24 UTC, Encord-davids commented on frontend_components/src/encord_active_components/frontend/src/components/explorer/Pagination.tsx
> +    (page + 1) * pageSize + pageSize
yep absolutely

2023-04-24 09:35 UTC, Encord-davids commented on src/encord_active/server/main.py
> +Project = Annotated[ProjectFileStructure, Depends(project)]
makes sense, what do you think about a `D` prefix for every dependency we inject? `DProjectFileStructure, DProject`

2023-04-24 09:37 UTC, Encord-davids commented on src/encord_active/lib/db/merged_metrics.py
> +            if columns and "identifier" not in columns:
the opposite, if people select specific `columns` they have to also select the `identifier`

2023-04-24 09:38 UTC, Encord-davids commented on src/encord_active/lib/db/helpers/tags.py
> +from encord_active.app.common.components.tags.utils import all_tags
yes yes

2023-04-24 09:39 UTC, Encord-davids commented on src/encord_active/lib/db/helpers/tags.py
> +from encord_active_components.components.explorer import GroupedTags
that is correct

2023-04-24 09:40 UTC, Encord-davids commented on src/encord_active/app/views/metrics.py
> +        print("Done", perf_counter() - start)
👍

2023-04-24 09:42 UTC, Encord-davids commented on src/encord_active/app/data_quality/sub_pages/explorer.py
> +        if output and output != output_state:
this should just be removed

2023-04-24 09:44 UTC, Encord-davids commented on src/encord_active/app/common/state.py
> +    def init(cls, target_paht: Path, project_dir: Path, refresh_projects: Callable[[], Any]):
🙈

2023-04-24 09:44 UTC, Encord-davids commented on src/encord_active/app/common/state.py
> +                target_path=target_paht,
🙈

2023-04-24 09:48 UTC, Encord-davids commented on src/encord_active/app/common/components/tags/utils.py
> +    return list({tag for tag_list in tag_list for tag in tag_list})
yas

2023-04-24 09:50 UTC, Encord-davids commented on src/encord_active/app/streamlit_entrypoint.py
> +    target_path = Path(target).resolve()
I think `expanduser + resolve` is the best

2023-04-24 09:52 UTC, frederik-encord commented on src/encord_active/server/main.py
> +Project = Annotated[ProjectFileStructure, Depends(project)]
Works for me. I used `Dep` in the premium api but `D` is fine as well.

2023-04-24 09:54 UTC, Encord-davids commented on src/encord_active/server/main.py
> +Project = Annotated[ProjectFileStructure, Depends(project)]
just check the docs and seems that they are also postfixing with `Dep` so lets go with that

2023-04-25 14:31 UTC, frederik-encord requested changes
Not enough space: Perhaps shrink some buttons and add tooltips
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/93145535/234306033-54242061-3e16-4685-9e06-223ccc9aea99.png">

Tooltips would be nice
<img width="252" alt="image" src="https://user-images.githubusercontent.com/93145535/234306351-5cc0b532-284c-417a-b3cd-a2d43f7f8faa.png">

When hovering the disabled button, it would be good to tell that one needs to select images first
<img width="370" alt="image" src="https://user-images.githubusercontent.com/93145535/234307007-d941bae5-7bd4-4bbf-b595-46a48fa4d5f6.png">

When everything is selected, the inverse operation would be nice (deselect all)
<img width="189" alt="image" src="https://user-images.githubusercontent.com/93145535/234307237-d11cdf44-e517-4b18-a6fe-4f7b8b0d7d82.png">

Could we sort there? It's hard to find a specific metric in the list.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/93145535/234309181-ef9f5903-8dd1-4c0c-a307-fdba8f2e3f10.png">

2023-04-27 11:54 UTC, frederik-encord submitted a review, later dismissed

2023-04-27 11:59 UTC, frederik-encord submitted a review, later dismissed

2023-04-27 12:12 UTC, frederik-encord approved these changes

2023-04-27 12:16 UTC, frederik-encord submitted a review, later dismissed

2023-04-27 12:56 UTC, frederik-encord approved these changes

2023-04-27 12:57 UTC, merged