feat: Move image loading to earlier, out of embeddings / metrics.
encord-team/encord-active pull request #401
Opened 2023-05-12 14:16 UTC by james-encord

First part of work on removing need to download images & the file structure as source of truth.

This moves image opening logic to earlier, so it can be more easily changed in follow-up PRs.

2023-05-15 06:54 UTC, Encord-davids commented
Great work! 
Could you just change the PR title to follow our [convention](https://docs.encord.com/active/docs/contributing#commit-convention)?🙏

2023-05-15 08:24 UTC, frederik-encord reviewed
Looking really good - a couple of things that we need to make sure to do is:
1. Update documentation around custom metrics - to use images instead of paths
2. Update example notebook that defines custom metric
3. See if there are any other places where we use the `iterator.iterate` in documentation or code and update that as well.
4. Write out in Discord that this will change with the next release.

2023-05-15 08:24 UTC, frederik-encord commented on src/encord_active/lib/common/utils.py
> +        return image.size
Pillow's `Image.size` is a tuple `(widht, height)` which is the oposite order of what's returned elsewhere.

2023-05-16 12:33 UTC, frederik-encord requested changes

2023-05-16 12:33 UTC, frederik-encord commented on src/encord_active/lib/common/iterator.py
> +                            image = download_image(data_unit["data_link"])
This one can be dangerous. These urls have TTL so might be invalid at the time we try to fetch them here.

2023-05-16 12:33 UTC, frederik-encord commented on src/encord_active/lib/common/utils.py
> +    return ocv_image
I would probably call this `convert_to_bgr` instead.
```suggestion
def convert_image_bgr(image: Image.Image) -> np.ndarray:
    rgb_image = image.convert("RGB")
    np_image = np.array(rgb_image)
    return np_image[:, :, ::-1].copy()
```

2023-05-16 12:33 UTC, frederik-encord commented on src/encord_active/lib/common/utils.py
> +    return ocv_image
☝🏻 Remember to update usages if you change the name ;-)

2023-05-16 12:33 UTC, frederik-encord commented on src/encord_active/lib/model_predictions/iterator.py
> +                yield du, Image.open(pth)
Not sure if we want a try/except here to avoid crashing the iterator?

2023-05-16 12:33 UTC, frederik-encord commented on src/encord_active/lib/common/iterator.py
> +                            image = Image.open(img_path.path)
perhaps a try/except here if images are, e.g., only half way downloaded or corrupted in some other way.

2023-05-19 13:30 UTC, frederik-encord submitted a review, later dismissed

2023-05-23 06:35 UTC, frederik-encord approved these changes

2023-05-23 08:23 UTC, merged