Feat (metrics): Video Color Densities
encord-team/encord-active pull request #587
Opened 2023-08-09 15:06 UTC by Gorkem-Encord

Average Red, Green, and Blue colors for the videos. The aim is to have a playable video in the explorer (maybe after clicking the image in the grid view).

2023-08-09 15:56 UTC, james-encord requested changes

2023-08-09 15:56 UTC, james-encord commented on src/encord_active/db/models.py
> +    metric_video_red_density: Optional[float] = MetricFieldTypeNormal
Could you add a comment to mark this as its own section of Data metrics.
# Whole video metrics or similar.

2023-08-10 07:26 UTC, Gorkem-Encord commented on frontend_components/encord_active_components/frontend/src/components/explorer/Explorer.tsx
> +          controls={true}
Agree, this is a bit beyond my expertise so leaving it to you or @Encord-davids .

2023-08-14 09:21 UTC, Encord-davids commented on frontend_components/encord_active_components/frontend/src/components/explorer/Explorer.tsx
> +          controls={true}
@frederik-encord Maybe something like "if video and average metric show controls"

2023-08-15 10:47 UTC, frederik-encord commented
Closing this PR as relevant changes were merged into branch `feat/avg-simple-metrics`

2023-08-15 10:47 UTC, closed without merging