Add: Active Cloud CTA
encord-team/encord-active pull request #686
Opened 2024-01-30 16:56 UTC by stephen-encord

I'll delete the branch once you review the changes

2024-01-30 18:54 UTC, frederik-encord requested changes
This looks good. Can we also add a banner in the very to of the page - this is pretty far down so folks might not see it.

2024-01-30 18:54 UTC, frederik-encord commented on README.md
> +✅ Integrate with annotation platform \
```suggestion
✅ Integrate with annotation platform  
✅ Filter by metadata  
```

2024-01-31 11:08 UTC, stephen-encord commented on README.md
> +✅ Integrate with annotation platform \
Added.

2024-02-01 10:57 UTC, frederik-encord approved these changes

2024-02-01 12:18 UTC, merged